# Generated by Django 6.0.5 on 2026-06-02 15:41

import api.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=api.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(default=api.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'Customer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(default=api.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Expense',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=api.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('priority', models.CharField(default='Normal', max_length=255)),
                ('read_at', models.DateTimeField(blank=True, db_column='readAt', null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(default=api.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('generated_by', models.CharField(blank=True, db_column='generatedBy', max_length=255, null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Report',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(default=api.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'Supplier',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=api.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(db_column='passwordHash', max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('ACCOUNTANT', 'Accountant'), ('WAREHOUSE', 'Warehouse')], default='STAFF', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=api.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('serial_code', models.CharField(db_column='serialCode', max_length=255, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('cost_price', models.DecimalField(db_column='costPrice', decimal_places=2, max_digits=12)),
                ('selling_price', models.DecimalField(db_column='sellingPrice', decimal_places=2, max_digits=12)),
                ('low_stock_at', models.IntegerField(db_column='lowStockAt', default=20)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('category', models.ForeignKey(db_column='categoryId', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api.category')),
                ('supplier', models.ForeignKey(blank=True, db_column='supplierId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.supplier')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.CharField(default=api.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('product', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.PROTECT, related_name='stock_logs', to='api.product')),
            ],
            options={
                'db_table': 'InventoryLog',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.CharField(default=api.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(db_column='invoiceNo', max_length=255, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(db_column='amountPaid', decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('payment_method', models.CharField(db_column='paymentMethod', max_length=255)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=20)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('customer', models.ForeignKey(db_column='customerId', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='api.customer')),
            ],
            options={
                'db_table': 'Sale',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.CharField(default=api.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(db_column='amountPaid', decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('due_date', models.DateTimeField(db_column='dueDate')),
                ('status', models.CharField(choices=[('CURRENT', 'Current'), ('OVERDUE', 'Overdue'), ('SETTLED', 'Settled')], default='CURRENT', max_length=20)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('customer', models.ForeignKey(db_column='customerId', on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='api.customer')),
                ('sale', models.OneToOneField(blank=True, db_column='saleId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt', to='api.sale')),
            ],
            options={
                'db_table': 'Debt',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.CharField(default=api.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(db_column='unitPrice', decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='api.product')),
                ('sale', models.ForeignKey(db_column='saleId', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.sale')),
            ],
            options={
                'db_table': 'SaleItem',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(default=api.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_at', models.DateTimeField(db_column='paidAt', default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(blank=True, db_column='customerId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.customer')),
                ('debt', models.ForeignKey(blank=True, db_column='debtId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.debt')),
                ('sale', models.ForeignKey(blank=True, db_column='saleId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.sale')),
                ('supplier', models.ForeignKey(blank=True, db_column='supplierId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.supplier')),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.CharField(default=api.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='productName', max_length=255)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.DecimalField(db_column='costPrice', decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(db_column='amountPaid', decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('delivered_at', models.DateTimeField(db_column='deliveredAt')),
                ('supplier', models.ForeignKey(db_column='supplierId', on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='api.supplier')),
            ],
            options={
                'db_table': 'Delivery',
            },
        ),
    ]
