# Generated by Django 6.0.5 on 2026-06-03 02:44

import api.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.CharField(default=api.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='productName', max_length=255)),
                ('quantity', models.IntegerField()),
                ('customer_name', models.CharField(blank=True, db_column='customerName', max_length=255, null=True)),
                ('date_requested', models.DateField(db_column='dateRequested')),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'CustomerRequest',
                'ordering': ['-date_requested'],
            },
        ),
    ]
