# Generated by Django 6.0.5 on 2026-06-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_import_polish_scrub_mask_stock'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customerrequest',
            index=models.Index(fields=['date_requested'], name='request_date_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrequest',
            index=models.Index(fields=['status'], name='request_status_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['due_date'], name='debt_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['status'], name='debt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['customer'], name='debt_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='expense_date_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='expense_category_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['product', 'created_at'], name='inventory_product_date_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['type'], name='inventory_type_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='product_category_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['quantity'], name='product_quantity_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['updated_at'], name='product_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_at'], name='sale_created_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer'], name='sale_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='sale_status_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale'], name='saleitem_sale_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['product'], name='saleitem_product_idx'),
        ),
    ]
